### PR TITLE
Clean up go modules.

### PR DESCRIPTION
**Pull request by SpeedyCoder**

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
This looks great, thanks. What commands did you run to produce this? It's possible it's better simply because I haven't tried re-resolving the dependencies with Go 1.12.

**Comment by johanbrandhorst** [comment]
CircleCI seems to think we can do one better:

```
git diff --exit-code

diff --git a/go.mod b/go.mod
index bafee95..b2ab97b 100644
--- a/go.mod
+++ b/go.mod
@@ -38,7 +38,6 @@ require (
 	golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
 	golang.org/x/sync v0.0.0-20190227155943-e225da77a7e6
 	golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 // indirect
-	google.golang.org/appengine v1.4.0 // indirect
 	google.golang.org/genproto v0.0.0-20190404172233-64821d5d2107 // indirect
 	google.golang.org/grpc v1.20.0
 	gotest.tools v2.2.0+incompatible // indirect
```
https://circleci.com/gh/johanbrandhorst/certify/498

Honestly though, if this is hard to reproduce, I can just remove the vendor check. It's never worked consistently for me.

**Comment by johanbrandhorst** [comment]
Hm, the generate error is a little more sinister. I don't know if we can update `moq`, as you can see the latest version has produced a generation error:

```
diff --git a/issuers/aws/mocks/client.mock.go b/issuers/aws/mocks/client.mock.go
index ee8d6f3..a31c670 100644
--- a/issuers/aws/mocks/client.mock.go
+++ b/issuers/aws/mocks/client.mock.go
@@ -6,6 +6,7 @@ package mocks
 import (
 	"github.com/aws/aws-sdk-go-v2/aws"
 	"github.com/aws/aws-sdk-go-v2/service/acmpca"
+	"github.com/johanbrandhorst/certify/vendor/github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface"
 	"sync"
 )
 
@@ -35,6 +36,10 @@ var (
 	lockACMPCAAPIMockWaitUntilCertificateIssuedWithContext              sync.RWMutex
 )
 
+// Ensure, that ACMPCAAPIMock does implement ACMPCAAPI.
+// If this is not the case, regenerate this file with moq.
+var _ acmpcaiface.ACMPCAAPI = &ACMPCAAPIMock{}
+
 // ACMPCAAPIMock is a mock implementation of ACMPCAAPI.
 //
 //     func TestSomethingThatUsesACMPCAAPI(t *testing.T) {
```

Also, you'll need to regenerate the protofiles in the test with a newer version of protoc-gen-go.

**Comment by SpeedyCoder** [comment]
Goland seems to be sticking `google.golang.org/appengine v1.4.0 // indirect` to `go.mod` file for some reason 😅 Will look at the other issue 👍

**Comment by johanbrandhorst** [comment]
I think if we can keep the previous version of `moq` and regenerate the proto files with the new `protoc-gen-go` we should be good.

**Comment by johanbrandhorst** [comment]
Looks like the vendor job is working again

**Comment by SpeedyCoder** [comment]
> I think if we can keep the previous version of `moq` and regenerate the proto files with the new `protoc-gen-go` we should be good.

cool will do that

**Comment by johanbrandhorst** [comment]
Looks like running go generate adds the appengine dependency back... I really don't understand it, but at this point I wouldn't hate just to remove the vendor job from `.circleci/config.yaml` if you can't get it to work.

**Comment by johanbrandhorst** [comment]
Ah, you'll need to copy the environment variable for that job, it runs without implicit module support. I think it's because of `moq`. Sorry :joy:.

**Comment by SpeedyCoder** [comment]
cool everything seems to be happy now

**Comment by SpeedyCoder** [comment]
awesome thank you

**Pull request merged**
