### PR TITLE
Add configurable logger

### LINKED ISSUE #36: Allow a logger to be configured
Probably just in the Certify struct for now, since any errors seen in the issuers should be propagate to Certify. The interface must default to a `noop` implementation that can safely be called. Perhaps just use `logrus` as well.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
The new logger interface can be used to log requests
to Certify. The interface is that proposed by
https://github.com/goph/logur. It provides adapters for
popular logging libraries.

Fixes #36, #51

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
@sagikazarmark what do you think?

**Comment by sagikazarmark** [comment]
Looks good to me! I'm glad you liked logur.

One tiny bit: if you are absolutely sure you will never use Trace and Warn, you can drop them from the interface, although adding them back would be a BC break. In an application that's not a big problem, in a library it might be.

Many people find `map[string]interface{}` too long. If you are one of them, you can shorten it by using `type LogFields map[string]interface{}` (not in the interface though). (Personally I don't mind the few extra characters)

I can see you imported logrus for the tests which added a number of new entries to `go.sum`. I'm currently playing with another library of mine and vanity imports (https://github.com/emperror/emperror). If the test goes well, I'm going to split logur as well so that it does not directly import all adapter libraries and you will be able to import them separately (with something like `adapter.logur.dev/logrus`). Just FYI. (Obviously that will happen in a backward compatible way, so existing packages using logur won't break)

**Comment by johanbrandhorst** [comment]
> Looks good to me! I'm glad you liked logur.
> 
> One tiny bit: if you are absolutely sure you will never use Trace and Warn, you can drop them from the interface, although adding them back would be a BC break. In an application that's not a big problem, in a library it might be.
> 
I think I will keep it in for now. Thanks for the tip.
> Many people find `map[string]interface{}` too long. If you are one of them, you can shorten it by using `type LogFields map[string]interface{}` (not in the interface though). (Personally I don't mind the few extra characters)
> 
I don't mind it here.
> I can see you imported logrus for the tests which added a number of new entries to `go.sum`. I'm currently playing with another library of mine and vanity imports (https://github.com/emperror/emperror). If the test goes well, I'm going to split logur as well so that it does not directly import all adapter libraries and you will be able to import them separately (with something like `adapter.logur.dev/logrus`). Just FYI. (Obviously that will happen in a backward compatible way, so existing packages using logur won't break)
This I am very interested in! I've already had users ask me to slim down the dependencies. What's your ETA? I wouldn't mind holding off on this for such a migration.

**Comment by sagikazarmark** [comment]
> This I am very interested in! I've already had users ask me to slim down the dependencies. What's your ETA? I wouldn't mind holding off on this for such a migration.

I'm still in the middle of migrating Emperror, have a few things to test before putting my stamp on it. I would say at least a few (2-3) weeks until I can get Logur migrated to this structure as well. Given you only use the library itself for testing (thanks to the dependency free interface), you could get rid of it for now, replace it with a custom implementation and put it back once the migration is done.

**Comment by johanbrandhorst** [comment]
Thanks for the tip, I removed the extra dependency again. Will consider adding it later to show users how to use it.

**Pull request merged**
